# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{acts_as_flashcard}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Bastien Vaucher"]
  s.date = %q{2011-01-15}
  s.description = %q{act_as_flashcard is an adaptation of the Anki space repetition algorithm for rails applications}
  s.email = %q{bastien.vaucher@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "GNU-LICENCE",
    "Gemfile",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "acts_as_flashcard.gemspec",
    "lib/acts_as_flashcard.rb",
    "lib/generators/flashcard/USAGE",
    "lib/generators/flashcard/flashcard_generator.rb",
    "lib/generators/flashcard/templates/add_flashcards_fields_migration.rb",
    "lib/generators/flashcard/templates/create_flashcards_migration.rb",
    "test/acts_as_flashcard_test.rb",
    "test/flashcards_migration_generator_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/bastien/acts_as_flashcard}
  s.licenses = ["GNU"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{flashcard space repetition algorithm}
  s.test_files = [
    "test/acts_as_flashcard_test.rb",
    "test/flashcards_migration_generator_test.rb",
    "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_runtime_dependency(%q<activerecord>, [">= 0"])
    else
      s.add_dependency(%q<activerecord>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_dependency(%q<activerecord>, [">= 0"])
    end
  else
    s.add_dependency(%q<activerecord>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
    s.add_dependency(%q<activerecord>, [">= 0"])
  end
end

